#!/usr/bin/env bash
# transfers a file from our client to a server

if [ -z "$1" ] || [ -z "$2" ];
    then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

elif [ "$#" -lt 4 ]; then
    file=$1
    ip=$2
    username=$3
    scp -o StrictHostKeyChecking=no "$file" "$username@$ip":~/

else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
