#!/usr/bin/env bash
# This script display "Best School" 10 times and "Hi" at the 9th iteration
count=1
while [ $count -le 10 ]
do
    echo Best School

    if [ "$count" = "9" ]
    then
	echo Hi
    fi

    ((count++))
done
