#!/usr/bin/env bash
# This script resolve localhost to 127.0.0.2, facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/^.*facebook.com$//g' ~/hosts.new
sed -i 's/^.*localhost$/127.0.0.2\tlocalhost/g' ~/hosts.new
sed -i '2 i 8.8.8.8\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
